# Generated by Django 5.2.6 on 2025-12-23 08:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text="Adresse postale de l'utilisateur", max_length=255, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Position géographique (latitude, longitude)', null=True, srid=4326, verbose_name='Coordonnées GPS'),
        ),
    ]
