# Generated by Django 5.2.6 on 2025-12-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_address_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Client Stripe'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Abonnement Stripe'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('trial', "Période d'essai"), ('active', 'Abonnement actif'), ('expired', 'Expiré'), ('canceled', 'Annulé')], default='trial', max_length=20, verbose_name="Statut de l'abonnement"),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='Date de fin des 3 mois gratuits', null=True, verbose_name="Fin de la période d'essai"),
        ),
    ]
