"""
Django settings for PanierFacile project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url
load_dotenv()
import psycopg2

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable must be set")

STRIPE_SECRET_KEY = os.getenv("SECRET_KEY_STRIPE")
STRIPE_PUBLISHABLE_KEY = os.getenv("PUBLISHABLE_KEY_STRIPE")
STRIPE_PRICE_ID = os.getenv("STRIPE_PRICE_ID")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['panier-facile.fr','www.panier-facile.fr','panier-facile.onrender.com', '127.0.0.1', 'localhost']

CSRF_TRUSTED_ORIGINS = ["https://panier-facile.fr","https://www.panier-facile.fr"]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Headers de sécurité HTTPS (activés uniquement en production)
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True

# Protection XSS et MIME sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Referrer Policy
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Requis par allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'authentication',
    'panier',
    'contact',  # Messages de contact et avis clients
    'core',  # Application core pour la logique metier
    'supermarkets',  # Gestion des enseignes (scrapers, matching produits)
    'django_celery_beat',  # Pour le scheduler Celery Beat
]

# Django allauth configuration
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth settings
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'optional'
LOGIN_REDIRECT_URL = '/panier/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
SOCIALACCOUNT_AUTO_SIGNUP = True

# Google OAuth configuration
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET'),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required by django-allauth
    'csp.middleware.CSPMiddleware',  # Content Security Policy
    # 'authentication.middleware.SubscriptionMiddleware',  # TEMPORAIREMENT DÉSACTIVÉ - À réactiver après migration
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
             BASE_DIR.joinpath('templates'),
             ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'panier.context_processors.stripe_keys',

            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL", "")

# Configuration de la base de données
if DATABASE_URL and DATABASE_URL.strip():
    # Production avec PostgreSQL + PostGIS
    # Ajouter django.contrib.gis aux INSTALLED_APPS pour la production
    if 'django.contrib.gis' not in INSTALLED_APPS:
        INSTALLED_APPS.insert(6, 'django.contrib.gis')

    try:
        DATABASES = {
            'default': dj_database_url.config(
                 default=DATABASE_URL,
                 conn_max_age=600,
                 ssl_require=False,
                 conn_health_checks=True,
            )
        }
        # Utiliser le backend PostGIS pour GeoDjango
        DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'
        # Force la désactivation de SSL
        DATABASES['default']['OPTIONS'] = {'sslmode': 'disable'}
    except Exception as e:
        # Fallback si erreur de parsing
        print(f"Warning: Could not parse DATABASE_URL: {e}")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # Développement local avec SQLite standard (sans GeoDjango)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

#Mot de passe personnalisé.
AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS':{
            'min_length' : 8,
        }
    },
    {
        'NAME': 'authentication.validators.ContainsLetterValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


STORAGES = {

    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
DOMAIN = os.getenv("DOMAIN")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'authentication.User'

LOGIN_REDIRECT_URL = 'home'

LOGIN_URL = 'login'



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# ============================================================================
# CELERY CONFIGURATION
# ============================================================================

# URL de connexion Redis pour Celery
# Format: redis://[:password]@host:port/db
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# Sérialisation des messages
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Fuseau horaire pour Celery (doit correspondre à TIME_ZONE)
CELERY_TIMEZONE = 'Europe/Paris'

# Options de performance
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max par tâche
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Avertissement à 25 minutes

# Configuration du résultat des tâches
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_EXPIRES = 3600  # Les résultats expirent après 1 heure

# Celery Beat (scheduler)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ============================================================================
# CONTENT SECURITY POLICY (CSP)
# ============================================================================

# Configuration CSP pour protéger contre les attaques XSS
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    "https://js.stripe.com",
    "https://cdn.jsdelivr.net",
    "https://unpkg.com",  # Leaflet.js
    "'unsafe-inline'",  # Nécessaire pour les scripts inline (à minimiser)
)
CSP_STYLE_SRC = (
    "'self'",
    "https://cdn.jsdelivr.net",
    "https://cdnjs.cloudflare.com",
    "https://unpkg.com",  # Leaflet CSS
    "'unsafe-inline'",  # Nécessaire pour Bootstrap et styles inline
)
CSP_IMG_SRC = (
    "'self'",
    "data:",
    "https:",  # Permet toutes les images HTTPS (pour OSM tiles, markers, etc.)
)
CSP_FONT_SRC = (
    "'self'",
    "https://cdnjs.cloudflare.com",
    "https://cdn.jsdelivr.net",
)
CSP_CONNECT_SRC = (
    "'self'",
    "https://api.stripe.com",
    "https://nominatim.openstreetmap.org",
    "https://overpass-api.de",
    "https://tile.openstreetmap.org",
    "https://api-partners.intermarche.com",
)
CSP_FRAME_SRC = (
    "https://js.stripe.com",
)

# En mode développement, désactiver CSP pour faciliter le debug
if DEBUG:
    CSP_REPORT_ONLY = True

# ========== INTERMARCHÉ API CONFIGURATION ==========

INTERMARCHE_API_KEY = os.getenv("INTERMARCHE_API_KEY", "")
INTERMARCHE_APP_NAME = os.getenv("INTERMARCHE_APP_NAME", "Panier-Facile")
INTERMARCHE_APP_VERSION = os.getenv("INTERMARCHE_APP_VERSION", "1.0.0")
