# Generated by Django 5.2.6 on 2025-12-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panier',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AddField(
            model_name='panier',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Indique si la notification de rappel (14 jours) a été envoyée'),
        ),
        migrations.AddField(
            model_name='panier',
            name='notification_sent_date',
            field=models.DateTimeField(blank=True, help_text="Date et heure d'envoi de la notification", null=True),
        ),
    ]
