# Generated by Django 5.2.6 on 2025-12-29 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0002_alter_panier_options_panier_notification_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Répondu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nom du client (peut être anonyme)', max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, help_text='Email du client (non publié)', max_length=254, verbose_name='Email')),
                ('rating', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Note')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('review', models.TextField(verbose_name='Avis')),
                ('would_recommend', models.BooleanField(default=False, verbose_name='Recommande')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('quantite', models.CharField(blank=True, max_length=50)),
                ('unite', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='Utilisateur qui a créé cette course', on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IngredientPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('checked', models.BooleanField(default=False, help_text="Indique si l'ingrédient a été coché")),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_paniers', to='panier.ingredient')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_paniers', to='panier.panier')),
            ],
            options={
                'verbose_name': 'Ingrédient du panier',
                'verbose_name_plural': 'Ingrédients du panier',
                'unique_together': {('panier', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='IntermarcheCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(help_text='Identifiant du magasin Intermarché', max_length=20)),
                ('store_name', models.CharField(blank=True, help_text='Nom du magasin Intermarché', max_length=255)),
                ('anonymous_cart_id', models.CharField(help_text='UUID du panier anonyme côté Intermarché', max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant total du panier en euros', max_digits=10)),
                ('items_count', models.IntegerField(default=0, help_text="Nombre d'articles dans le panier")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé à Intermarché'), ('completed', 'Commande finalisée'), ('failed', 'Échec')], default='draft', max_length=20)),
                ('sync_response', models.JSONField(blank=True, help_text="Réponse complète de l'API Intermarché lors de la synchronisation", null=True)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur en cas d'échec")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du panier Intermarché')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermarche_carts', to='panier.panier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermarche_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panier Intermarché',
                'verbose_name_plural': 'Paniers Intermarché',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='panier_inte_user_id_3b3910_idx'), models.Index(fields=['store_id', 'created_at'], name='panier_inte_store_i_00925d_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntermarcheProductMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(default='scraping', help_text="Identifiant du magasin Intermarché (ex: 08177) ou 'scraping'", max_length=20)),
                ('intermarche_product_id', models.CharField(blank=True, help_text='ID unique du produit Intermarché (API uniquement)', max_length=100, null=True)),
                ('intermarche_product_ean13', models.CharField(blank=True, help_text='Code-barres EAN13 du produit', max_length=13)),
                ('intermarche_item_parent_id', models.CharField(blank=True, help_text="ID parent de l'item (pour les produits avec variantes)", max_length=100, null=True)),
                ('product_name', models.CharField(help_text='Nom du produit (scraping)', max_length=255)),
                ('product_label', models.CharField(blank=True, help_text='Libellé du produit (API)', max_length=255)),
                ('product_brand', models.CharField(blank=True, help_text='Marque du produit', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire du produit', max_digits=10, null=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire du produit (API - deprecated, use price)', max_digits=10, null=True)),
                ('product_url', models.URLField(blank=True, help_text='URL du produit sur le site Intermarché', null=True)),
                ('product_image_url', models.URLField(blank=True, help_text="URL de l'image du produit")),
                ('is_available', models.BooleanField(default=True, help_text='Disponibilité du produit')),
                ('match_score', models.FloatField(default=0.0, help_text='Score de pertinence du matching (0.0 à 1.0)')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour du match')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du match')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermarche_matches', to='panier.ingredient')),
            ],
            options={
                'verbose_name': 'Correspondance produit Intermarché',
                'verbose_name_plural': 'Correspondances produits Intermarché',
                'indexes': [models.Index(fields=['ingredient', 'store_id'], name='panier_inte_ingredi_be84f0_idx'), models.Index(fields=['store_id', 'last_updated'], name='panier_inte_store_i_fdf96b_idx')],
            },
        ),
    ]
